# Generated by Django 4.2 on 2023-04-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'notes',
            },
        ),
    ]
